inputSet:
  name: Build_Camera_Service_Application_Using_React_Node_js_and_Mysql_1743672450548-push-trigger-input-set
  identifier: Build_Camera_Service_Application_Using_React_Node_js_and_Mysql_1743672450548pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_Camera_Service_Application_Using_React_Node_js_and_Mysql_1743672450548
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
